"""empty message

Revision ID: d0d4cc27c536
Revises: dcf464c5b493
Create Date: 2023-08-03 23:42:03.055325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d4cc27c536'
down_revision = 'dcf464c5b493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('eye_color', sa.String(length=40), nullable=True),
    sa.Column('people_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_fav'], ['fav.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('terrain', sa.String(length=40), nullable=True),
    sa.Column('planets_fav', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planets_fav'], ['fav.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('fav')
    # ### end Alembic commands ###
